# -*- coding: utf-8 -*-
"""HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXw5ENs6n7qmctTV7KX1SKntZZC4P8hY
"""

from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"